# Generated by Django 6.0.5 on 2026-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emoji', models.CharField(default='🌿', max_length=8)),
                ('description', models.TextField()),
                ('full_desc', models.TextField(blank=True, help_text='Detailed description shown in product modal')),
                ('eco_benefit', models.CharField(max_length=200)),
                ('eco_score', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B')], default='A', max_length=4)),
                ('price', models.CharField(help_text='e.g. ₹120 / pack of 20', max_length=80)),
                ('usage', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('color', models.CharField(default='#e8f2eb', help_text='CSS hex color for card background', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fc_products',
                'ordering': ['name'],
            },
        ),
    ]
