# Generated by Django 5.0.6 on 2026-09-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/references/'),
        ),
    ]
