# Generated by Django 6.0.5 on 2026-05-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('quantity', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'db_table': 'fc_enquiries',
                'ordering': ['-submitted_on'],
            },
        ),
    ]
