# Generated by Django 6.0.5 on 2026-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('temple_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('flower_type', models.CharField(choices=[('Marigold', 'Marigold (Genda)'), ('Rose', 'Rose'), ('Jasmine', 'Jasmine'), ('Lotus', 'Lotus'), ('Hibiscus', 'Hibiscus'), ('Mixed', 'Mixed Flowers'), ('Other', 'Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Collected', 'Collected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pickup Request',
                'db_table': 'fc_pickup_requests',
                'ordering': ['-submitted_on'],
            },
        ),
    ]
